name: Vagrant image (OS X / VirtualBox)
maintainers:
- Jim Minter <jminter@redhat.com>
description: |
  This image requires Vagrant and VirtualBox and is suitable for Apple OS X
  hosts.
howto: |
  ```sh
  # Install VirtualBox from https://www.virtualbox.org/wiki/Downloads before
  # proceeding

  # Install Vagrant from http://www.vagrantup.com/downloads.html before
  # proceeding

  # Download and install the box image
  vagrant box add $IMAGE \
    $URL

  # Create a clean working directory for the image
  mkdir -p $HOME/vagrant/$IMAGE-SHORT
  cd $HOME/vagrant/$IMAGE-SHORT
  vagrant init $IMAGE

  # Launch the image
  vagrant up

  # Then connect to your vagrant box via the VirtualBox console
  ```
