name: OpenShift 3.0.2 base image
maintainers:
- Jim Minter <jminter@redhat.com>
description: |
  This image provides a base instance of OpenShift 3.0.2, including the
  master and node components, examples, GUI and web browser.  All S2I builder
  images are also included, but Internet connectivity is required to run.

  This image includes builder images and is vanilla, so is handy for SAs and
  consultants to replicate issues / experiment with the product with Internet
  connectivity.
layer:
  cpus: 2
  mem: 4096
